In [3]:
import mxnet as mx
import numpy as np

In [4]:
data = mx.nd.array([np.nan,np.inf,np.NINF,0]);

In [5]:
data


[ nan  inf -inf   0.]
<NDArray 4 @cpu(0)>

In [6]:
mx.nd.contrib.isfinite(data)


[0. 0. 0. 1.]
<NDArray 4 @cpu(0)>

In [7]:
mx.nd.contrib.isinf(data)


[0. 1. 1. 0.]
<NDArray 4 @cpu(0)>

In [8]:
mx.nd.contrib.isnan(data)


[1. 0. 0. 0.]
<NDArray 4 @cpu(0)>