Hardmax implementations 

In [13]:
import numpy as np
data= np.random.rand(2,3,4)
print(data)
import tensorflow as tf
import time
print(tf)
# a=tf.constant(1.0)
start_time=time.time()
b=tf.Variable(data)#tf.Variable([[[2,3,4],[1,2,3]],[[1,1,1],[1,2,3]]])
init_op = tf.global_variables_initializer()
with tf.Session() as sess:    
#     print(sess.run(a))
    sess.run(init_op)
#     print(sess.run(b))
#     print("argmax")
#     print(sess.run(tf.argmax(b,axis=1))) #returns the index of the highest value along that axis (axis=1 compares column-wise, axis=2 row-wise)
    print("hardmax")
    print(sess.run(tf.contrib.seq2seq.hardmax(b)))
    print("hardmax via argmax one hot")
    print(sess.run(tf.one_hot(tf.argmax(b,-1),tf.shape(b)[-1])))
    end_time=time.time()
    print("time needed"+str(end_time-start_time))

[[[0.18651888 0.29437149 0.45589573 0.55928469]
  [0.1951702  0.50387834 0.38563502 0.49604304]
  [0.12411261 0.67440557 0.50830552 0.67146303]]

 [[0.52552375 0.06349533 0.78590277 0.36544202]
  [0.6055249  0.317296   0.42477562 0.34462548]
  [0.55422445 0.68032915 0.93749125 0.89412014]]]
<module 'tensorflow' from '/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py'>
hardmax
[[[0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 [[0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]]]
hardmax via argmax one hot
[[[0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 [[0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]]]
time needed0.059676170349121094


In [2]:
import torch
print(torch)
start_time=time.time()
x = torch.tensor([[[2,3,4],[1,2,3]],[[1,1,1],[1,2,3]]])
values, indices = torch.max(x, 2) #0 does it across z, 2 across row, 1 across column
print(values)
print(indices)
end_time=time.time()
print("time needed"+str(end_time-start_time))

<module 'torch' from '/anaconda3/lib/python3.6/site-packages/torch/__init__.py'>
tensor([[4, 3],
        [1, 3]])
tensor([[2, 2],
        [0, 2]])
time needed0.00185394287109375


In [12]:

import mxnet as mx
import numpy as np
import time
start_time=time.time()
# x = np.asarray([[[2,3,4],[1,2,3]],[[1,1,1],[1,2,3]]])#np.random.rand(2,2,3)
xn = mx.nd.array(data)

xn_r = mx.nd.reshape(xn, shape=(2,12))
xn_e = mx.nd.eye(xn_r.shape[1], dtype=data.dtype)[mx.nd.argmax(xn_r, axis=1)]

hardmax_output = mx.nd.reshape(xn_e, shape=xn.shape)
print(hardmax_output)
end_time=time.time()
print("time needed"+str(end_time-start_time))
print(mx.nd.contrib.hardmax(data))




[[[0. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>
time needed0.0034580230712890625


AttributeError: 'numpy.ndarray' object has no attribute 'one_hot'

In [10]:
import mxnet as mx
import numpy as np
x = np.asarray([[[2,3,4],[1,2,3]],[[1,1,1],[1,2,3]]])#np.random.rand(2,2,3)
xn = mx.nd.array(x)
print('onehotargmax'+str(mx.nd.one_hot(mx.nd.argmax(xn,-1),xn.shape[-1])))

onehotargmax
[[[0. 0. 1.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 0. 1.]]]
<NDArray 2x2x3 @cpu(0)>
