In [5]:
import mxnet as mx
import numpy as np
input_array = mx.nd.array([[ 0., 1., 2.],[ 3., 4., 5.]])

In [2]:
input_array


[[0. 1. 2.]
 [3. 4. 5.]]
<NDArray 2x3 @cpu(0)>

In [3]:
mx.nd.SoftmaxActivation(input_array).asnumpy()

array([[0.09003057, 0.24472848, 0.66524094],
       [0.09003057, 0.24472848, 0.66524094]], dtype=float32)

In [6]:
np.argmax(input_array.asnumpy())

5

In [7]:
np.argmax(input_array.asnumpy(),axis=0)

array([1, 1, 1])

In [8]:
np.argmax(input_array.asnumpy(),axis=1)

array([2, 2])

In [9]:
np.max(input_array.asnumpy(),axis=0)

array([3., 4., 5.], dtype=float32)

In [10]:
np.max(input_array.asnumpy(),axis=1)

array([2., 5.], dtype=float32)

In [12]:
mx.nd.contrib.hardmax(input_array)


[[0. 0. 1.]
 [0. 0. 1.]]
<NDArray 2x3 @cpu(0)>